services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: bookdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:5000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: bookdb
      DB_USER: postgres
      DB_PASSWORD: password
    depends_on:
      - db

volumes:
  db_data:
